// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createAccessToken = `-- name: CreateAccessToken :exec
INSERT INTO access_tokens (user_id, token_hash, expires_at)
VALUES (?, ?, ?)
`

type CreateAccessTokenParams struct {
	UserID    uint64    `db:"user_id"`
	TokenHash []byte    `db:"token_hash"`
	ExpiresAt time.Time `db:"expires_at"`
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAccessToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES (?, ?, ?)
`

type CreateRefreshTokenParams struct {
	UserID    uint64    `db:"user_id"`
	TokenHash []byte    `db:"token_hash"`
	ExpiresAt time.Time `db:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (username, email, display_name, password_hash)
VALUES (?, ?, ?, ?)
`

type CreateUserParams struct {
	Username     string `db:"username"`
	Email        string `db:"email"`
	DisplayName  string `db:"display_name"`
	PasswordHash string `db:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
	)
}

const getRefreshSessionForUpdate = `-- name: GetRefreshSessionForUpdate :one
SELECT
  refresh.id AS refresh_token_id,
  u.id AS user_id,
  u.username,
  u.email,
  u.display_name,
  u.created_at,
  u.updated_at
FROM refresh_tokens AS refresh
JOIN users AS u ON u.id = refresh.user_id
WHERE refresh.token_hash = ?
  AND refresh.revoked_at IS NULL
  AND refresh.expires_at > ?
LIMIT 1
FOR UPDATE
`

type GetRefreshSessionForUpdateParams struct {
	TokenHash []byte    `db:"token_hash"`
	ExpiresAt time.Time `db:"expires_at"`
}

type GetRefreshSessionForUpdateRow struct {
	RefreshTokenID uint64    `db:"refresh_token_id"`
	UserID         uint64    `db:"user_id"`
	Username       string    `db:"username"`
	Email          string    `db:"email"`
	DisplayName    string    `db:"display_name"`
	CreatedAt      time.Time `db:"created_at"`
	UpdatedAt      time.Time `db:"updated_at"`
}

func (q *Queries) GetRefreshSessionForUpdate(ctx context.Context, arg GetRefreshSessionForUpdateParams) (GetRefreshSessionForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshSessionForUpdate, arg.TokenHash, arg.ExpiresAt)
	var i GetRefreshSessionForUpdateRow
	err := row.Scan(
		&i.RefreshTokenID,
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAccessToken = `-- name: GetUserByAccessToken :one
SELECT
  u.id AS user_id,
  u.username,
  u.email,
  u.display_name,
  u.created_at,
  u.updated_at
FROM access_tokens AS access
JOIN users AS u ON u.id = access.user_id
WHERE access.token_hash = ?
  AND access.revoked_at IS NULL
  AND access.expires_at > ?
LIMIT 1
`

type GetUserByAccessTokenParams struct {
	TokenHash []byte    `db:"token_hash"`
	ExpiresAt time.Time `db:"expires_at"`
}

type GetUserByAccessTokenRow struct {
	UserID      uint64    `db:"user_id"`
	Username    string    `db:"username"`
	Email       string    `db:"email"`
	DisplayName string    `db:"display_name"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}

func (q *Queries) GetUserByAccessToken(ctx context.Context, arg GetUserByAccessTokenParams) (GetUserByAccessTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByAccessToken, arg.TokenHash, arg.ExpiresAt)
	var i GetUserByAccessTokenRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, display_name, password_hash, created_at, updated_at
FROM users
WHERE email = ?
LIMIT 1
`

type GetUserByEmailRow struct {
	ID           uint64    `db:"id"`
	Username     string    `db:"username"`
	Email        string    `db:"email"`
	DisplayName  string    `db:"display_name"`
	PasswordHash string    `db:"password_hash"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAccessTokenByHash = `-- name: RevokeAccessTokenByHash :exec
UPDATE access_tokens
SET revoked_at = ?
WHERE token_hash = ?
  AND revoked_at IS NULL
`

type RevokeAccessTokenByHashParams struct {
	RevokedAt sql.NullTime `db:"revoked_at"`
	TokenHash []byte       `db:"token_hash"`
}

func (q *Queries) RevokeAccessTokenByHash(ctx context.Context, arg RevokeAccessTokenByHashParams) error {
	_, err := q.db.ExecContext(ctx, revokeAccessTokenByHash, arg.RevokedAt, arg.TokenHash)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE refresh_tokens
SET revoked_at = ?
WHERE token_hash = ?
  AND revoked_at IS NULL
`

type RevokeRefreshTokenByHashParams struct {
	RevokedAt sql.NullTime `db:"revoked_at"`
	TokenHash []byte       `db:"token_hash"`
}

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, arg RevokeRefreshTokenByHashParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokenByHash, arg.RevokedAt, arg.TokenHash)
	return err
}

const revokeRefreshTokenByID = `-- name: RevokeRefreshTokenByID :exec
UPDATE refresh_tokens
SET revoked_at = ?
WHERE id = ?
  AND revoked_at IS NULL
`

type RevokeRefreshTokenByIDParams struct {
	RevokedAt sql.NullTime `db:"revoked_at"`
	ID        uint64       `db:"id"`
}

func (q *Queries) RevokeRefreshTokenByID(ctx context.Context, arg RevokeRefreshTokenByIDParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokenByID, arg.RevokedAt, arg.ID)
	return err
}
