// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const acceptContactRelationship = `-- name: AcceptContactRelationship :execresult
UPDATE contact_relationships
SET status = 'accepted'
WHERE id = ?
  AND status = 'pending'
  AND requested_by_user_id <> ?
  AND (
    lower_user_id = ?
    OR higher_user_id = ?
  )
`

type AcceptContactRelationshipParams struct {
	RelationshipID uint64 `db:"relationship_id"`
	CurrentUserID  uint64 `db:"current_user_id"`
}

func (q *Queries) AcceptContactRelationship(ctx context.Context, arg AcceptContactRelationshipParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, acceptContactRelationship,
		arg.RelationshipID,
		arg.CurrentUserID,
		arg.CurrentUserID,
		arg.CurrentUserID,
	)
}

const contactRelationshipStatus = `-- name: ContactRelationshipStatus :one
SELECT status
FROM contact_relationships
WHERE lower_user_id = ?
  AND higher_user_id = ?
LIMIT 1
`

type ContactRelationshipStatusParams struct {
	LowerUserID  uint64 `db:"lower_user_id"`
	HigherUserID uint64 `db:"higher_user_id"`
}

func (q *Queries) ContactRelationshipStatus(ctx context.Context, arg ContactRelationshipStatusParams) (string, error) {
	row := q.db.QueryRowContext(ctx, contactRelationshipStatus, arg.LowerUserID, arg.HigherUserID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const createContactRelationship = `-- name: CreateContactRelationship :execresult
INSERT INTO contact_relationships (
  lower_user_id,
  higher_user_id,
  requested_by_user_id,
  status
)
VALUES (?, ?, ?, 'pending')
`

type CreateContactRelationshipParams struct {
	LowerUserID       uint64 `db:"lower_user_id"`
	HigherUserID      uint64 `db:"higher_user_id"`
	RequestedByUserID uint64 `db:"requested_by_user_id"`
}

func (q *Queries) CreateContactRelationship(ctx context.Context, arg CreateContactRelationshipParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createContactRelationship, arg.LowerUserID, arg.HigherUserID, arg.RequestedByUserID)
}

const findPublicUserByUsername = `-- name: FindPublicUserByUsername :one
SELECT id, username, display_name, created_at
FROM users
WHERE username = ?
LIMIT 1
`

type FindPublicUserByUsernameRow struct {
	ID          uint64    `db:"id"`
	Username    string    `db:"username"`
	DisplayName string    `db:"display_name"`
	CreatedAt   time.Time `db:"created_at"`
}

func (q *Queries) FindPublicUserByUsername(ctx context.Context, username string) (FindPublicUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, findPublicUserByUsername, username)
	var i FindPublicUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getContactRelationshipByID = `-- name: GetContactRelationshipByID :one
SELECT
  relationship.id,
  relationship.lower_user_id,
  relationship.higher_user_id,
  relationship.requested_by_user_id,
  relationship.status,
  relationship.created_at,
  relationship.updated_at,
  other_user.id AS other_user_id,
  other_user.username AS other_username,
  other_user.display_name AS other_display_name,
  other_user.created_at AS other_created_at
FROM contact_relationships AS relationship
JOIN users AS other_user
  ON other_user.id = CASE
    WHEN relationship.lower_user_id = ? THEN relationship.higher_user_id
    ELSE relationship.lower_user_id
  END
WHERE relationship.id = ?
  AND (
    relationship.lower_user_id = ?
    OR relationship.higher_user_id = ?
  )
LIMIT 1
`

type GetContactRelationshipByIDParams struct {
	CurrentUserID  uint64 `db:"current_user_id"`
	RelationshipID uint64 `db:"relationship_id"`
}

type GetContactRelationshipByIDRow struct {
	ID                uint64    `db:"id"`
	LowerUserID       uint64    `db:"lower_user_id"`
	HigherUserID      uint64    `db:"higher_user_id"`
	RequestedByUserID uint64    `db:"requested_by_user_id"`
	Status            string    `db:"status"`
	CreatedAt         time.Time `db:"created_at"`
	UpdatedAt         time.Time `db:"updated_at"`
	OtherUserID       uint64    `db:"other_user_id"`
	OtherUsername     string    `db:"other_username"`
	OtherDisplayName  string    `db:"other_display_name"`
	OtherCreatedAt    time.Time `db:"other_created_at"`
}

func (q *Queries) GetContactRelationshipByID(ctx context.Context, arg GetContactRelationshipByIDParams) (GetContactRelationshipByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getContactRelationshipByID,
		arg.CurrentUserID,
		arg.RelationshipID,
		arg.CurrentUserID,
		arg.CurrentUserID,
	)
	var i GetContactRelationshipByIDRow
	err := row.Scan(
		&i.ID,
		&i.LowerUserID,
		&i.HigherUserID,
		&i.RequestedByUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OtherUserID,
		&i.OtherUsername,
		&i.OtherDisplayName,
		&i.OtherCreatedAt,
	)
	return i, err
}

const listAcceptedContacts = `-- name: ListAcceptedContacts :many
SELECT
  relationship.id AS relationship_id,
  other_user.id AS user_id,
  other_user.username,
  other_user.display_name,
  other_user.created_at,
  relationship.updated_at AS connected_at
FROM contact_relationships AS relationship
JOIN users AS other_user
  ON other_user.id = CASE
    WHEN relationship.lower_user_id = ? THEN relationship.higher_user_id
    ELSE relationship.lower_user_id
  END
WHERE relationship.status = 'accepted'
  AND (
    relationship.lower_user_id = ?
    OR relationship.higher_user_id = ?
  )
ORDER BY other_user.display_name, other_user.username, other_user.id
LIMIT 500
`

type ListAcceptedContactsParams struct {
	CurrentUserID uint64 `db:"current_user_id"`
}

type ListAcceptedContactsRow struct {
	RelationshipID uint64    `db:"relationship_id"`
	UserID         uint64    `db:"user_id"`
	Username       string    `db:"username"`
	DisplayName    string    `db:"display_name"`
	CreatedAt      time.Time `db:"created_at"`
	ConnectedAt    time.Time `db:"connected_at"`
}

func (q *Queries) ListAcceptedContacts(ctx context.Context, arg ListAcceptedContactsParams) ([]ListAcceptedContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAcceptedContacts, arg.CurrentUserID, arg.CurrentUserID, arg.CurrentUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAcceptedContactsRow{}
	for rows.Next() {
		var i ListAcceptedContactsRow
		if err := rows.Scan(
			&i.RelationshipID,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.CreatedAt,
			&i.ConnectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingContactRelationships = `-- name: ListPendingContactRelationships :many
SELECT
  relationship.id,
  relationship.lower_user_id,
  relationship.higher_user_id,
  relationship.requested_by_user_id,
  relationship.status,
  relationship.created_at,
  relationship.updated_at,
  other_user.id AS other_user_id,
  other_user.username AS other_username,
  other_user.display_name AS other_display_name,
  other_user.created_at AS other_created_at
FROM contact_relationships AS relationship
JOIN users AS other_user
  ON other_user.id = CASE
    WHEN relationship.lower_user_id = ? THEN relationship.higher_user_id
    ELSE relationship.lower_user_id
  END
WHERE relationship.status = 'pending'
  AND (
    relationship.lower_user_id = ?
    OR relationship.higher_user_id = ?
  )
ORDER BY relationship.updated_at DESC, relationship.id DESC
LIMIT 100
`

type ListPendingContactRelationshipsParams struct {
	CurrentUserID uint64 `db:"current_user_id"`
}

type ListPendingContactRelationshipsRow struct {
	ID                uint64    `db:"id"`
	LowerUserID       uint64    `db:"lower_user_id"`
	HigherUserID      uint64    `db:"higher_user_id"`
	RequestedByUserID uint64    `db:"requested_by_user_id"`
	Status            string    `db:"status"`
	CreatedAt         time.Time `db:"created_at"`
	UpdatedAt         time.Time `db:"updated_at"`
	OtherUserID       uint64    `db:"other_user_id"`
	OtherUsername     string    `db:"other_username"`
	OtherDisplayName  string    `db:"other_display_name"`
	OtherCreatedAt    time.Time `db:"other_created_at"`
}

func (q *Queries) ListPendingContactRelationships(ctx context.Context, arg ListPendingContactRelationshipsParams) ([]ListPendingContactRelationshipsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingContactRelationships, arg.CurrentUserID, arg.CurrentUserID, arg.CurrentUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingContactRelationshipsRow{}
	for rows.Next() {
		var i ListPendingContactRelationshipsRow
		if err := rows.Scan(
			&i.ID,
			&i.LowerUserID,
			&i.HigherUserID,
			&i.RequestedByUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OtherUserID,
			&i.OtherUsername,
			&i.OtherDisplayName,
			&i.OtherCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectContactRelationship = `-- name: RejectContactRelationship :execresult
DELETE FROM contact_relationships
WHERE id = ?
  AND status = 'pending'
  AND requested_by_user_id <> ?
  AND (
    lower_user_id = ?
    OR higher_user_id = ?
  )
`

type RejectContactRelationshipParams struct {
	RelationshipID uint64 `db:"relationship_id"`
	CurrentUserID  uint64 `db:"current_user_id"`
}

func (q *Queries) RejectContactRelationship(ctx context.Context, arg RejectContactRelationshipParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, rejectContactRelationship,
		arg.RelationshipID,
		arg.CurrentUserID,
		arg.CurrentUserID,
		arg.CurrentUserID,
	)
}

const removeAcceptedContact = `-- name: RemoveAcceptedContact :execresult
DELETE FROM contact_relationships
WHERE lower_user_id = ?
  AND higher_user_id = ?
  AND status = 'accepted'
`

type RemoveAcceptedContactParams struct {
	LowerUserID  uint64 `db:"lower_user_id"`
	HigherUserID uint64 `db:"higher_user_id"`
}

func (q *Queries) RemoveAcceptedContact(ctx context.Context, arg RemoveAcceptedContactParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeAcceptedContact, arg.LowerUserID, arg.HigherUserID)
}
