// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createConversationMember = `-- name: CreateConversationMember :exec
INSERT INTO conversation_members (conversation_id, user_id)
VALUES (?, ?)
`

type CreateConversationMemberParams struct {
	ConversationID uint64 `db:"conversation_id"`
	UserID         uint64 `db:"user_id"`
}

func (q *Queries) CreateConversationMember(ctx context.Context, arg CreateConversationMemberParams) error {
	_, err := q.db.ExecContext(ctx, createConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const createDirectConversation = `-- name: CreateDirectConversation :execresult
INSERT INTO conversations (
  kind,
  direct_lower_user_id,
  direct_higher_user_id,
  created_by_user_id
)
VALUES ('direct', ?, ?, ?)
`

type CreateDirectConversationParams struct {
	DirectLowerUserID  uint64 `db:"direct_lower_user_id"`
	DirectHigherUserID uint64 `db:"direct_higher_user_id"`
	CreatedByUserID    uint64 `db:"created_by_user_id"`
}

func (q *Queries) CreateDirectConversation(ctx context.Context, arg CreateDirectConversationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDirectConversation, arg.DirectLowerUserID, arg.DirectHigherUserID, arg.CreatedByUserID)
}

const getDirectConversationByPair = `-- name: GetDirectConversationByPair :one
SELECT
  conversation.id,
  conversation.kind,
  conversation.created_at,
  conversation.updated_at,
  other_user.id AS peer_user_id,
  other_user.username AS peer_username,
  other_user.display_name AS peer_display_name,
  other_user.created_at AS peer_created_at
FROM conversations AS conversation
JOIN users AS other_user
  ON other_user.id = CASE
    WHEN conversation.direct_lower_user_id = ? THEN conversation.direct_higher_user_id
    ELSE conversation.direct_lower_user_id
  END
WHERE conversation.direct_lower_user_id = ?
  AND conversation.direct_higher_user_id = ?
LIMIT 1
`

type GetDirectConversationByPairParams struct {
	CurrentUserID uint64 `db:"current_user_id"`
	LowerUserID   uint64 `db:"lower_user_id"`
	HigherUserID  uint64 `db:"higher_user_id"`
}

type GetDirectConversationByPairRow struct {
	ID              uint64    `db:"id"`
	Kind            string    `db:"kind"`
	CreatedAt       time.Time `db:"created_at"`
	UpdatedAt       time.Time `db:"updated_at"`
	PeerUserID      uint64    `db:"peer_user_id"`
	PeerUsername    string    `db:"peer_username"`
	PeerDisplayName string    `db:"peer_display_name"`
	PeerCreatedAt   time.Time `db:"peer_created_at"`
}

func (q *Queries) GetDirectConversationByPair(ctx context.Context, arg GetDirectConversationByPairParams) (GetDirectConversationByPairRow, error) {
	row := q.db.QueryRowContext(ctx, getDirectConversationByPair, arg.CurrentUserID, arg.LowerUserID, arg.HigherUserID)
	var i GetDirectConversationByPairRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeerUserID,
		&i.PeerUsername,
		&i.PeerDisplayName,
		&i.PeerCreatedAt,
	)
	return i, err
}

const listConversationsForUser = `-- name: ListConversationsForUser :many
SELECT
  conversation.id,
  conversation.kind,
  conversation.created_at,
  conversation.updated_at,
  other_user.id AS peer_user_id,
  other_user.username AS peer_username,
  other_user.display_name AS peer_display_name,
  other_user.created_at AS peer_created_at
FROM conversation_members AS membership
JOIN conversations AS conversation ON conversation.id = membership.conversation_id
JOIN users AS other_user
  ON other_user.id = CASE
    WHEN conversation.direct_lower_user_id = ? THEN conversation.direct_higher_user_id
    ELSE conversation.direct_lower_user_id
  END
WHERE membership.user_id = ?
ORDER BY conversation.updated_at DESC, conversation.id DESC
LIMIT 200
`

type ListConversationsForUserParams struct {
	CurrentUserID uint64 `db:"current_user_id"`
}

type ListConversationsForUserRow struct {
	ID              uint64    `db:"id"`
	Kind            string    `db:"kind"`
	CreatedAt       time.Time `db:"created_at"`
	UpdatedAt       time.Time `db:"updated_at"`
	PeerUserID      uint64    `db:"peer_user_id"`
	PeerUsername    string    `db:"peer_username"`
	PeerDisplayName string    `db:"peer_display_name"`
	PeerCreatedAt   time.Time `db:"peer_created_at"`
}

func (q *Queries) ListConversationsForUser(ctx context.Context, arg ListConversationsForUserParams) ([]ListConversationsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsForUser, arg.CurrentUserID, arg.CurrentUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsForUserRow{}
	for rows.Next() {
		var i ListConversationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PeerUserID,
			&i.PeerUsername,
			&i.PeerDisplayName,
			&i.PeerCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
