// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createConversationMember = `-- name: CreateConversationMember :exec
INSERT INTO conversation_members (conversation_id, user_id)
VALUES (?, ?)
`

type CreateConversationMemberParams struct {
	ConversationID uint64 `db:"conversation_id"`
	UserID         uint64 `db:"user_id"`
}

func (q *Queries) CreateConversationMember(ctx context.Context, arg CreateConversationMemberParams) error {
	_, err := q.db.ExecContext(ctx, createConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const createDirectConversation = `-- name: CreateDirectConversation :execresult
INSERT INTO conversations (
  kind,
  direct_lower_user_id,
  direct_higher_user_id,
  created_by_user_id
)
VALUES ('direct', ?, ?, ?)
`

type CreateDirectConversationParams struct {
	DirectLowerUserID  uint64 `db:"direct_lower_user_id"`
	DirectHigherUserID uint64 `db:"direct_higher_user_id"`
	CreatedByUserID    uint64 `db:"created_by_user_id"`
}

func (q *Queries) CreateDirectConversation(ctx context.Context, arg CreateDirectConversationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDirectConversation, arg.DirectLowerUserID, arg.DirectHigherUserID, arg.CreatedByUserID)
}

const getDirectConversationByPair = `-- name: GetDirectConversationByPair :one
SELECT
  conversation.id,
  conversation.kind,
  conversation.created_at,
  conversation.updated_at,
  (
    SELECT COUNT(*)
    FROM messages AS unread_message
    WHERE unread_message.conversation_id = conversation.id
      AND unread_message.sender_id <> ?
      AND unread_message.sequence > membership.last_read_sequence
      AND unread_message.recalled_at IS NULL
      AND NOT EXISTS (
        SELECT 1
        FROM message_deletions AS deletion
        WHERE deletion.message_id = unread_message.id
          AND deletion.user_id = ?
      )
  ) AS unread_count,
  latest_message.sequence AS last_message_sequence,
  latest_message.kind AS last_message_kind,
  latest_message.body AS last_message_body,
  latest_file.filename AS last_message_file_name,
  other_user.id AS peer_user_id,
  other_user.username AS peer_username,
  other_user.display_name AS peer_display_name,
  other_user.avatar_content_type AS peer_avatar_content_type,
  other_user.created_at AS peer_created_at
FROM conversations AS conversation
JOIN conversation_members AS membership
  ON membership.conversation_id = conversation.id
  AND membership.user_id = ?
  AND membership.is_active = TRUE
LEFT JOIN messages AS latest_message
  ON latest_message.id = (
    SELECT visible_message.id
    FROM messages AS visible_message
    WHERE visible_message.conversation_id = conversation.id
      AND visible_message.recalled_at IS NULL
      AND NOT EXISTS (
        SELECT 1
        FROM message_deletions AS deletion
        WHERE deletion.message_id = visible_message.id
          AND deletion.user_id = ?
      )
    ORDER BY visible_message.sequence DESC
    LIMIT 1
  )
LEFT JOIN message_files AS latest_file ON latest_file.id = latest_message.file_id
JOIN users AS other_user
  ON other_user.id = CASE
    WHEN conversation.direct_lower_user_id = ? THEN conversation.direct_higher_user_id
    ELSE conversation.direct_lower_user_id
  END
WHERE conversation.direct_lower_user_id = ?
  AND conversation.direct_higher_user_id = ?
LIMIT 1
`

type GetDirectConversationByPairParams struct {
	CurrentUserID uint64 `db:"current_user_id"`
	LowerUserID   uint64 `db:"lower_user_id"`
	HigherUserID  uint64 `db:"higher_user_id"`
}

type GetDirectConversationByPairRow struct {
	ID                    uint64         `db:"id"`
	Kind                  string         `db:"kind"`
	CreatedAt             time.Time      `db:"created_at"`
	UpdatedAt             time.Time      `db:"updated_at"`
	UnreadCount           int64          `db:"unread_count"`
	LastMessageSequence   sql.NullInt64  `db:"last_message_sequence"`
	LastMessageKind       sql.NullString `db:"last_message_kind"`
	LastMessageBody       sql.NullString `db:"last_message_body"`
	LastMessageFileName   sql.NullString `db:"last_message_file_name"`
	PeerUserID            uint64         `db:"peer_user_id"`
	PeerUsername          string         `db:"peer_username"`
	PeerDisplayName       string         `db:"peer_display_name"`
	PeerAvatarContentType sql.NullString `db:"peer_avatar_content_type"`
	PeerCreatedAt         time.Time      `db:"peer_created_at"`
}

func (q *Queries) GetDirectConversationByPair(ctx context.Context, arg GetDirectConversationByPairParams) (GetDirectConversationByPairRow, error) {
	row := q.db.QueryRowContext(ctx, getDirectConversationByPair,
		arg.CurrentUserID,
		arg.CurrentUserID,
		arg.CurrentUserID,
		arg.CurrentUserID,
		arg.CurrentUserID,
		arg.LowerUserID,
		arg.HigherUserID,
	)
	var i GetDirectConversationByPairRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnreadCount,
		&i.LastMessageSequence,
		&i.LastMessageKind,
		&i.LastMessageBody,
		&i.LastMessageFileName,
		&i.PeerUserID,
		&i.PeerUsername,
		&i.PeerDisplayName,
		&i.PeerAvatarContentType,
		&i.PeerCreatedAt,
	)
	return i, err
}

const isConversationMemberForRead = `-- name: IsConversationMemberForRead :one
SELECT EXISTS(
  SELECT 1
  FROM conversation_members
  WHERE conversation_id = ?
    AND user_id = ?
    AND is_active = TRUE
) AS is_member
`

type IsConversationMemberForReadParams struct {
	ConversationID uint64 `db:"conversation_id"`
	UserID         uint64 `db:"user_id"`
}

func (q *Queries) IsConversationMemberForRead(ctx context.Context, arg IsConversationMemberForReadParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isConversationMemberForRead, arg.ConversationID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listConversationsForUser = `-- name: ListConversationsForUser :many
SELECT
  conversation.id,
  conversation.kind,
  conversation.created_at,
  conversation.updated_at,
  (
    SELECT COUNT(*)
    FROM messages AS unread_message
    WHERE unread_message.conversation_id = conversation.id
      AND unread_message.sender_id <> ?
      AND unread_message.sequence > membership.last_read_sequence
      AND unread_message.recalled_at IS NULL
      AND NOT EXISTS (
        SELECT 1
        FROM message_deletions AS deletion
        WHERE deletion.message_id = unread_message.id
          AND deletion.user_id = ?
      )
  ) AS unread_count,
  latest_message.sequence AS last_message_sequence,
  latest_message.kind AS last_message_kind,
  latest_message.body AS last_message_body,
  latest_file.filename AS last_message_file_name,
  other_user.id AS peer_user_id,
  other_user.username AS peer_username,
  other_user.display_name AS peer_display_name,
  other_user.avatar_content_type AS peer_avatar_content_type,
  other_user.created_at AS peer_created_at
FROM conversation_members AS membership
JOIN conversations AS conversation ON conversation.id = membership.conversation_id
LEFT JOIN messages AS latest_message
  ON latest_message.id = (
    SELECT visible_message.id
    FROM messages AS visible_message
    WHERE visible_message.conversation_id = conversation.id
      AND visible_message.recalled_at IS NULL
      AND NOT EXISTS (
        SELECT 1
        FROM message_deletions AS deletion
        WHERE deletion.message_id = visible_message.id
          AND deletion.user_id = ?
      )
    ORDER BY visible_message.sequence DESC
    LIMIT 1
  )
LEFT JOIN message_files AS latest_file ON latest_file.id = latest_message.file_id
JOIN users AS other_user
  ON other_user.id = CASE
    WHEN conversation.direct_lower_user_id = ? THEN conversation.direct_higher_user_id
    ELSE conversation.direct_lower_user_id
  END
WHERE membership.user_id = ?
  AND membership.is_active = TRUE
ORDER BY conversation.updated_at DESC, conversation.id DESC
LIMIT 200
`

type ListConversationsForUserParams struct {
	CurrentUserID uint64 `db:"current_user_id"`
}

type ListConversationsForUserRow struct {
	ID                    uint64         `db:"id"`
	Kind                  string         `db:"kind"`
	CreatedAt             time.Time      `db:"created_at"`
	UpdatedAt             time.Time      `db:"updated_at"`
	UnreadCount           int64          `db:"unread_count"`
	LastMessageSequence   sql.NullInt64  `db:"last_message_sequence"`
	LastMessageKind       sql.NullString `db:"last_message_kind"`
	LastMessageBody       sql.NullString `db:"last_message_body"`
	LastMessageFileName   sql.NullString `db:"last_message_file_name"`
	PeerUserID            uint64         `db:"peer_user_id"`
	PeerUsername          string         `db:"peer_username"`
	PeerDisplayName       string         `db:"peer_display_name"`
	PeerAvatarContentType sql.NullString `db:"peer_avatar_content_type"`
	PeerCreatedAt         time.Time      `db:"peer_created_at"`
}

func (q *Queries) ListConversationsForUser(ctx context.Context, arg ListConversationsForUserParams) ([]ListConversationsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsForUser,
		arg.CurrentUserID,
		arg.CurrentUserID,
		arg.CurrentUserID,
		arg.CurrentUserID,
		arg.CurrentUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsForUserRow{}
	for rows.Next() {
		var i ListConversationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnreadCount,
			&i.LastMessageSequence,
			&i.LastMessageKind,
			&i.LastMessageBody,
			&i.LastMessageFileName,
			&i.PeerUserID,
			&i.PeerUsername,
			&i.PeerDisplayName,
			&i.PeerAvatarContentType,
			&i.PeerCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationRead = `-- name: MarkConversationRead :exec
UPDATE conversation_members AS membership
JOIN conversations AS conversation ON conversation.id = membership.conversation_id
SET membership.last_read_sequence = GREATEST(
  membership.last_read_sequence,
  LEAST(?, conversation.next_sequence - 1)
)
WHERE membership.conversation_id = ?
  AND membership.user_id = ?
  AND membership.is_active = TRUE
`

type MarkConversationReadParams struct {
	Sequence       interface{} `db:"sequence"`
	ConversationID uint64      `db:"conversation_id"`
	UserID         uint64      `db:"user_id"`
}

func (q *Queries) MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error {
	_, err := q.db.ExecContext(ctx, markConversationRead, arg.Sequence, arg.ConversationID, arg.UserID)
	return err
}
