// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const advanceConversationSequence = `-- name: AdvanceConversationSequence :exec
UPDATE conversations
SET next_sequence = next_sequence + 1,
    updated_at = CURRENT_TIMESTAMP(6)
WHERE id = ?
`

func (q *Queries) AdvanceConversationSequence(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, advanceConversationSequence, id)
	return err
}

const createMessage = `-- name: CreateMessage :execresult
INSERT INTO messages (
  conversation_id,
  sender_id,
  client_message_id,
  sequence,
  body
)
VALUES (?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ConversationID  uint64 `db:"conversation_id"`
	SenderID        uint64 `db:"sender_id"`
	ClientMessageID string `db:"client_message_id"`
	Sequence        uint64 `db:"sequence"`
	Body            string `db:"body"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.ClientMessageID,
		arg.Sequence,
		arg.Body,
	)
}

const getMessageByClientID = `-- name: GetMessageByClientID :one
SELECT
  message.id,
  message.conversation_id,
  message.sender_id,
  sender.username AS sender_username,
  sender.display_name AS sender_display_name,
  sender.created_at AS sender_created_at,
  message.client_message_id,
  message.sequence,
  message.body,
  message.created_at
FROM messages AS message
JOIN users AS sender ON sender.id = message.sender_id
WHERE message.conversation_id = ?
  AND message.sender_id = ?
  AND message.client_message_id = ?
LIMIT 1
`

type GetMessageByClientIDParams struct {
	ConversationID  uint64 `db:"conversation_id"`
	SenderID        uint64 `db:"sender_id"`
	ClientMessageID string `db:"client_message_id"`
}

type GetMessageByClientIDRow struct {
	ID                uint64    `db:"id"`
	ConversationID    uint64    `db:"conversation_id"`
	SenderID          uint64    `db:"sender_id"`
	SenderUsername    string    `db:"sender_username"`
	SenderDisplayName string    `db:"sender_display_name"`
	SenderCreatedAt   time.Time `db:"sender_created_at"`
	ClientMessageID   string    `db:"client_message_id"`
	Sequence          uint64    `db:"sequence"`
	Body              string    `db:"body"`
	CreatedAt         time.Time `db:"created_at"`
}

func (q *Queries) GetMessageByClientID(ctx context.Context, arg GetMessageByClientIDParams) (GetMessageByClientIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageByClientID, arg.ConversationID, arg.SenderID, arg.ClientMessageID)
	var i GetMessageByClientIDRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.SenderUsername,
		&i.SenderDisplayName,
		&i.SenderCreatedAt,
		&i.ClientMessageID,
		&i.Sequence,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS (
  SELECT 1
  FROM conversation_members
  WHERE conversation_id = ?
    AND user_id = ?
) AS is_member
`

type IsConversationMemberParams struct {
	ConversationID uint64 `db:"conversation_id"`
	UserID         uint64 `db:"user_id"`
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listLatestMessages = `-- name: ListLatestMessages :many
SELECT
  message.id,
  message.conversation_id,
  message.sender_id,
  sender.username AS sender_username,
  sender.display_name AS sender_display_name,
  sender.created_at AS sender_created_at,
  message.client_message_id,
  message.sequence,
  message.body,
  message.created_at
FROM messages AS message
JOIN users AS sender ON sender.id = message.sender_id
WHERE message.conversation_id = ?
ORDER BY message.sequence DESC
LIMIT ?
`

type ListLatestMessagesParams struct {
	ConversationID uint64 `db:"conversation_id"`
	Limit          int32  `db:"limit"`
}

type ListLatestMessagesRow struct {
	ID                uint64    `db:"id"`
	ConversationID    uint64    `db:"conversation_id"`
	SenderID          uint64    `db:"sender_id"`
	SenderUsername    string    `db:"sender_username"`
	SenderDisplayName string    `db:"sender_display_name"`
	SenderCreatedAt   time.Time `db:"sender_created_at"`
	ClientMessageID   string    `db:"client_message_id"`
	Sequence          uint64    `db:"sequence"`
	Body              string    `db:"body"`
	CreatedAt         time.Time `db:"created_at"`
}

func (q *Queries) ListLatestMessages(ctx context.Context, arg ListLatestMessagesParams) ([]ListLatestMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestMessagesRow{}
	for rows.Next() {
		var i ListLatestMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.SenderUsername,
			&i.SenderDisplayName,
			&i.SenderCreatedAt,
			&i.ClientMessageID,
			&i.Sequence,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT
  message.id,
  message.conversation_id,
  message.sender_id,
  sender.username AS sender_username,
  sender.display_name AS sender_display_name,
  sender.created_at AS sender_created_at,
  message.client_message_id,
  message.sequence,
  message.body,
  message.created_at
FROM messages AS message
JOIN users AS sender ON sender.id = message.sender_id
WHERE message.conversation_id = ?
  AND message.sequence < ?
ORDER BY message.sequence DESC
LIMIT ?
`

type ListMessagesBeforeParams struct {
	ConversationID uint64 `db:"conversation_id"`
	BeforeSequence uint64 `db:"before_sequence"`
	Limit          int32  `db:"limit"`
}

type ListMessagesBeforeRow struct {
	ID                uint64    `db:"id"`
	ConversationID    uint64    `db:"conversation_id"`
	SenderID          uint64    `db:"sender_id"`
	SenderUsername    string    `db:"sender_username"`
	SenderDisplayName string    `db:"sender_display_name"`
	SenderCreatedAt   time.Time `db:"sender_created_at"`
	ClientMessageID   string    `db:"client_message_id"`
	Sequence          uint64    `db:"sequence"`
	Body              string    `db:"body"`
	CreatedAt         time.Time `db:"created_at"`
}

func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]ListMessagesBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBefore, arg.ConversationID, arg.BeforeSequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesBeforeRow{}
	for rows.Next() {
		var i ListMessagesBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.SenderUsername,
			&i.SenderDisplayName,
			&i.SenderCreatedAt,
			&i.ClientMessageID,
			&i.Sequence,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConversationForMessage = `-- name: LockConversationForMessage :one
SELECT conversation.next_sequence
FROM conversations AS conversation
JOIN conversation_members AS membership
  ON membership.conversation_id = conversation.id
WHERE conversation.id = ?
  AND membership.user_id = ?
LIMIT 1
FOR UPDATE
`

type LockConversationForMessageParams struct {
	ConversationID uint64 `db:"conversation_id"`
	UserID         uint64 `db:"user_id"`
}

func (q *Queries) LockConversationForMessage(ctx context.Context, arg LockConversationForMessageParams) (uint64, error) {
	row := q.db.QueryRowContext(ctx, lockConversationForMessage, arg.ConversationID, arg.UserID)
	var next_sequence uint64
	err := row.Scan(&next_sequence)
	return next_sequence, err
}
