// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const advanceConversationSequence = `-- name: AdvanceConversationSequence :exec
UPDATE conversations
SET next_sequence = next_sequence + 1,
    updated_at = CURRENT_TIMESTAMP(6)
WHERE id = ?
`

func (q *Queries) AdvanceConversationSequence(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, advanceConversationSequence, id)
	return err
}

const createMessage = `-- name: CreateMessage :execresult
INSERT INTO messages (
  conversation_id,
  sender_id,
  client_message_id,
  sequence,
  kind,
  body,
  image_id,
  file_id
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ConversationID  uint64        `db:"conversation_id"`
	SenderID        uint64        `db:"sender_id"`
	ClientMessageID string        `db:"client_message_id"`
	Sequence        uint64        `db:"sequence"`
	Kind            string        `db:"kind"`
	Body            string        `db:"body"`
	ImageID         sql.NullInt64 `db:"image_id"`
	FileID          sql.NullInt64 `db:"file_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.ClientMessageID,
		arg.Sequence,
		arg.Kind,
		arg.Body,
		arg.ImageID,
		arg.FileID,
	)
}

const createMessageFile = `-- name: CreateMessageFile :execresult
INSERT INTO message_files (
  uploader_id,
  filename,
  content_type,
  byte_size,
  data
)
VALUES (?, ?, ?, ?, ?)
`

type CreateMessageFileParams struct {
	UploaderID  uint64 `db:"uploader_id"`
	Filename    string `db:"filename"`
	ContentType string `db:"content_type"`
	ByteSize    uint32 `db:"byte_size"`
	Data        []byte `db:"data"`
}

func (q *Queries) CreateMessageFile(ctx context.Context, arg CreateMessageFileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMessageFile,
		arg.UploaderID,
		arg.Filename,
		arg.ContentType,
		arg.ByteSize,
		arg.Data,
	)
}

const createMessageImage = `-- name: CreateMessageImage :execresult
INSERT INTO message_images (
  uploader_id,
  content_type,
  byte_size,
  data
)
VALUES (?, ?, ?, ?)
`

type CreateMessageImageParams struct {
	UploaderID  uint64 `db:"uploader_id"`
	ContentType string `db:"content_type"`
	ByteSize    uint32 `db:"byte_size"`
	Data        []byte `db:"data"`
}

func (q *Queries) CreateMessageImage(ctx context.Context, arg CreateMessageImageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMessageImage,
		arg.UploaderID,
		arg.ContentType,
		arg.ByteSize,
		arg.Data,
	)
}

const getMessageByClientID = `-- name: GetMessageByClientID :one
SELECT
  message.id,
  message.conversation_id,
  message.sender_id,
  sender.username AS sender_username,
  sender.display_name AS sender_display_name,
  sender.avatar_content_type AS sender_avatar_content_type,
  sender.created_at AS sender_created_at,
  message.client_message_id,
  message.sequence,
  message.kind,
  message.body,
  message.image_id,
  image.content_type AS image_content_type,
  image.byte_size AS image_byte_size,
  message.file_id,
  file.filename AS file_filename,
  file.content_type AS file_content_type,
  file.byte_size AS file_byte_size,
  message.created_at
FROM messages AS message
JOIN users AS sender ON sender.id = message.sender_id
LEFT JOIN message_images AS image ON image.id = message.image_id
LEFT JOIN message_files AS file ON file.id = message.file_id
WHERE message.conversation_id = ?
  AND message.sender_id = ?
  AND message.client_message_id = ?
LIMIT 1
`

type GetMessageByClientIDParams struct {
	ConversationID  uint64 `db:"conversation_id"`
	SenderID        uint64 `db:"sender_id"`
	ClientMessageID string `db:"client_message_id"`
}

type GetMessageByClientIDRow struct {
	ID                      uint64         `db:"id"`
	ConversationID          uint64         `db:"conversation_id"`
	SenderID                uint64         `db:"sender_id"`
	SenderUsername          string         `db:"sender_username"`
	SenderDisplayName       string         `db:"sender_display_name"`
	SenderAvatarContentType sql.NullString `db:"sender_avatar_content_type"`
	SenderCreatedAt         time.Time      `db:"sender_created_at"`
	ClientMessageID         string         `db:"client_message_id"`
	Sequence                uint64         `db:"sequence"`
	Kind                    string         `db:"kind"`
	Body                    string         `db:"body"`
	ImageID                 sql.NullInt64  `db:"image_id"`
	ImageContentType        sql.NullString `db:"image_content_type"`
	ImageByteSize           sql.NullInt32  `db:"image_byte_size"`
	FileID                  sql.NullInt64  `db:"file_id"`
	FileFilename            sql.NullString `db:"file_filename"`
	FileContentType         sql.NullString `db:"file_content_type"`
	FileByteSize            sql.NullInt32  `db:"file_byte_size"`
	CreatedAt               time.Time      `db:"created_at"`
}

func (q *Queries) GetMessageByClientID(ctx context.Context, arg GetMessageByClientIDParams) (GetMessageByClientIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageByClientID, arg.ConversationID, arg.SenderID, arg.ClientMessageID)
	var i GetMessageByClientIDRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.SenderUsername,
		&i.SenderDisplayName,
		&i.SenderAvatarContentType,
		&i.SenderCreatedAt,
		&i.ClientMessageID,
		&i.Sequence,
		&i.Kind,
		&i.Body,
		&i.ImageID,
		&i.ImageContentType,
		&i.ImageByteSize,
		&i.FileID,
		&i.FileFilename,
		&i.FileContentType,
		&i.FileByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageFileForMember = `-- name: GetMessageFileForMember :one
SELECT
  file.filename,
  file.content_type,
  file.byte_size,
  file.data
FROM message_files AS file
JOIN messages AS message ON message.file_id = file.id
JOIN conversation_members AS membership
  ON membership.conversation_id = message.conversation_id
WHERE file.id = ?
  AND membership.user_id = ?
  AND message.recalled_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM message_deletions AS deletion
    WHERE deletion.message_id = message.id
      AND deletion.user_id = ?
  )
LIMIT 1
`

type GetMessageFileForMemberParams struct {
	FileID uint64 `db:"file_id"`
	UserID uint64 `db:"user_id"`
}

type GetMessageFileForMemberRow struct {
	Filename    string `db:"filename"`
	ContentType string `db:"content_type"`
	ByteSize    uint32 `db:"byte_size"`
	Data        []byte `db:"data"`
}

func (q *Queries) GetMessageFileForMember(ctx context.Context, arg GetMessageFileForMemberParams) (GetMessageFileForMemberRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageFileForMember, arg.FileID, arg.UserID, arg.UserID)
	var i GetMessageFileForMemberRow
	err := row.Scan(
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.Data,
	)
	return i, err
}

const getMessageImageForMember = `-- name: GetMessageImageForMember :one
SELECT
  image.content_type,
  image.byte_size,
  image.data
FROM message_images AS image
JOIN messages AS message ON message.image_id = image.id
JOIN conversation_members AS membership
  ON membership.conversation_id = message.conversation_id
WHERE image.id = ?
  AND membership.user_id = ?
  AND message.recalled_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM message_deletions AS deletion
    WHERE deletion.message_id = message.id
      AND deletion.user_id = ?
  )
LIMIT 1
`

type GetMessageImageForMemberParams struct {
	ImageID uint64 `db:"image_id"`
	UserID  uint64 `db:"user_id"`
}

type GetMessageImageForMemberRow struct {
	ContentType string `db:"content_type"`
	ByteSize    uint32 `db:"byte_size"`
	Data        []byte `db:"data"`
}

func (q *Queries) GetMessageImageForMember(ctx context.Context, arg GetMessageImageForMemberParams) (GetMessageImageForMemberRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageImageForMember, arg.ImageID, arg.UserID, arg.UserID)
	var i GetMessageImageForMemberRow
	err := row.Scan(&i.ContentType, &i.ByteSize, &i.Data)
	return i, err
}

const hideMessageForUser = `-- name: HideMessageForUser :exec
INSERT IGNORE INTO message_deletions (message_id, user_id)
SELECT message.id, ?
FROM messages AS message
JOIN conversation_members AS membership
  ON membership.conversation_id = message.conversation_id
WHERE message.id = ?
  AND message.conversation_id = ?
  AND membership.user_id = ?
`

type HideMessageForUserParams struct {
	UserID         uint64 `db:"user_id"`
	MessageID      uint64 `db:"message_id"`
	ConversationID uint64 `db:"conversation_id"`
}

func (q *Queries) HideMessageForUser(ctx context.Context, arg HideMessageForUserParams) error {
	_, err := q.db.ExecContext(ctx, hideMessageForUser,
		arg.UserID,
		arg.MessageID,
		arg.ConversationID,
		arg.UserID,
	)
	return err
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS (
  SELECT 1
  FROM conversation_members
  WHERE conversation_id = ?
    AND user_id = ?
) AS is_member
`

type IsConversationMemberParams struct {
	ConversationID uint64 `db:"conversation_id"`
	UserID         uint64 `db:"user_id"`
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listConversationMemberIDs = `-- name: ListConversationMemberIDs :many
SELECT user_id
FROM conversation_members
WHERE conversation_id = ?
ORDER BY user_id ASC
`

func (q *Queries) ListConversationMemberIDs(ctx context.Context, conversationID uint64) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, listConversationMemberIDs, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var user_id uint64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestMessages = `-- name: ListLatestMessages :many
SELECT
  message.id,
  message.conversation_id,
  message.sender_id,
  sender.username AS sender_username,
  sender.display_name AS sender_display_name,
  sender.avatar_content_type AS sender_avatar_content_type,
  sender.created_at AS sender_created_at,
  message.client_message_id,
  message.sequence,
  message.kind,
  message.body,
  message.image_id,
  image.content_type AS image_content_type,
  image.byte_size AS image_byte_size,
  message.file_id,
  file.filename AS file_filename,
  file.content_type AS file_content_type,
  file.byte_size AS file_byte_size,
  message.created_at
FROM messages AS message
JOIN users AS sender ON sender.id = message.sender_id
LEFT JOIN message_images AS image ON image.id = message.image_id
LEFT JOIN message_files AS file ON file.id = message.file_id
WHERE message.conversation_id = ?
  AND message.recalled_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM message_deletions AS deletion
    WHERE deletion.message_id = message.id
      AND deletion.user_id = ?
  )
ORDER BY message.sequence DESC
LIMIT ?
`

type ListLatestMessagesParams struct {
	ConversationID uint64 `db:"conversation_id"`
	UserID         uint64 `db:"user_id"`
	Limit          int32  `db:"limit"`
}

type ListLatestMessagesRow struct {
	ID                      uint64         `db:"id"`
	ConversationID          uint64         `db:"conversation_id"`
	SenderID                uint64         `db:"sender_id"`
	SenderUsername          string         `db:"sender_username"`
	SenderDisplayName       string         `db:"sender_display_name"`
	SenderAvatarContentType sql.NullString `db:"sender_avatar_content_type"`
	SenderCreatedAt         time.Time      `db:"sender_created_at"`
	ClientMessageID         string         `db:"client_message_id"`
	Sequence                uint64         `db:"sequence"`
	Kind                    string         `db:"kind"`
	Body                    string         `db:"body"`
	ImageID                 sql.NullInt64  `db:"image_id"`
	ImageContentType        sql.NullString `db:"image_content_type"`
	ImageByteSize           sql.NullInt32  `db:"image_byte_size"`
	FileID                  sql.NullInt64  `db:"file_id"`
	FileFilename            sql.NullString `db:"file_filename"`
	FileContentType         sql.NullString `db:"file_content_type"`
	FileByteSize            sql.NullInt32  `db:"file_byte_size"`
	CreatedAt               time.Time      `db:"created_at"`
}

func (q *Queries) ListLatestMessages(ctx context.Context, arg ListLatestMessagesParams) ([]ListLatestMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestMessages, arg.ConversationID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestMessagesRow{}
	for rows.Next() {
		var i ListLatestMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.SenderUsername,
			&i.SenderDisplayName,
			&i.SenderAvatarContentType,
			&i.SenderCreatedAt,
			&i.ClientMessageID,
			&i.Sequence,
			&i.Kind,
			&i.Body,
			&i.ImageID,
			&i.ImageContentType,
			&i.ImageByteSize,
			&i.FileID,
			&i.FileFilename,
			&i.FileContentType,
			&i.FileByteSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAfter = `-- name: ListMessagesAfter :many
SELECT
  message.id,
  message.conversation_id,
  message.sender_id,
  sender.username AS sender_username,
  sender.display_name AS sender_display_name,
  sender.avatar_content_type AS sender_avatar_content_type,
  sender.created_at AS sender_created_at,
  message.client_message_id,
  message.sequence,
  message.kind,
  message.body,
  message.image_id,
  image.content_type AS image_content_type,
  image.byte_size AS image_byte_size,
  message.file_id,
  file.filename AS file_filename,
  file.content_type AS file_content_type,
  file.byte_size AS file_byte_size,
  message.created_at
FROM messages AS message
JOIN users AS sender ON sender.id = message.sender_id
LEFT JOIN message_images AS image ON image.id = message.image_id
LEFT JOIN message_files AS file ON file.id = message.file_id
WHERE message.conversation_id = ?
  AND message.sequence > ?
  AND message.recalled_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM message_deletions AS deletion
    WHERE deletion.message_id = message.id
      AND deletion.user_id = ?
  )
ORDER BY message.sequence ASC
LIMIT ?
`

type ListMessagesAfterParams struct {
	ConversationID uint64 `db:"conversation_id"`
	AfterSequence  uint64 `db:"after_sequence"`
	UserID         uint64 `db:"user_id"`
	Limit          int32  `db:"limit"`
}

type ListMessagesAfterRow struct {
	ID                      uint64         `db:"id"`
	ConversationID          uint64         `db:"conversation_id"`
	SenderID                uint64         `db:"sender_id"`
	SenderUsername          string         `db:"sender_username"`
	SenderDisplayName       string         `db:"sender_display_name"`
	SenderAvatarContentType sql.NullString `db:"sender_avatar_content_type"`
	SenderCreatedAt         time.Time      `db:"sender_created_at"`
	ClientMessageID         string         `db:"client_message_id"`
	Sequence                uint64         `db:"sequence"`
	Kind                    string         `db:"kind"`
	Body                    string         `db:"body"`
	ImageID                 sql.NullInt64  `db:"image_id"`
	ImageContentType        sql.NullString `db:"image_content_type"`
	ImageByteSize           sql.NullInt32  `db:"image_byte_size"`
	FileID                  sql.NullInt64  `db:"file_id"`
	FileFilename            sql.NullString `db:"file_filename"`
	FileContentType         sql.NullString `db:"file_content_type"`
	FileByteSize            sql.NullInt32  `db:"file_byte_size"`
	CreatedAt               time.Time      `db:"created_at"`
}

func (q *Queries) ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]ListMessagesAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesAfter,
		arg.ConversationID,
		arg.AfterSequence,
		arg.UserID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesAfterRow{}
	for rows.Next() {
		var i ListMessagesAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.SenderUsername,
			&i.SenderDisplayName,
			&i.SenderAvatarContentType,
			&i.SenderCreatedAt,
			&i.ClientMessageID,
			&i.Sequence,
			&i.Kind,
			&i.Body,
			&i.ImageID,
			&i.ImageContentType,
			&i.ImageByteSize,
			&i.FileID,
			&i.FileFilename,
			&i.FileContentType,
			&i.FileByteSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT
  message.id,
  message.conversation_id,
  message.sender_id,
  sender.username AS sender_username,
  sender.display_name AS sender_display_name,
  sender.avatar_content_type AS sender_avatar_content_type,
  sender.created_at AS sender_created_at,
  message.client_message_id,
  message.sequence,
  message.kind,
  message.body,
  message.image_id,
  image.content_type AS image_content_type,
  image.byte_size AS image_byte_size,
  message.file_id,
  file.filename AS file_filename,
  file.content_type AS file_content_type,
  file.byte_size AS file_byte_size,
  message.created_at
FROM messages AS message
JOIN users AS sender ON sender.id = message.sender_id
LEFT JOIN message_images AS image ON image.id = message.image_id
LEFT JOIN message_files AS file ON file.id = message.file_id
WHERE message.conversation_id = ?
  AND message.sequence < ?
  AND message.recalled_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM message_deletions AS deletion
    WHERE deletion.message_id = message.id
      AND deletion.user_id = ?
  )
ORDER BY message.sequence DESC
LIMIT ?
`

type ListMessagesBeforeParams struct {
	ConversationID uint64 `db:"conversation_id"`
	BeforeSequence uint64 `db:"before_sequence"`
	UserID         uint64 `db:"user_id"`
	Limit          int32  `db:"limit"`
}

type ListMessagesBeforeRow struct {
	ID                      uint64         `db:"id"`
	ConversationID          uint64         `db:"conversation_id"`
	SenderID                uint64         `db:"sender_id"`
	SenderUsername          string         `db:"sender_username"`
	SenderDisplayName       string         `db:"sender_display_name"`
	SenderAvatarContentType sql.NullString `db:"sender_avatar_content_type"`
	SenderCreatedAt         time.Time      `db:"sender_created_at"`
	ClientMessageID         string         `db:"client_message_id"`
	Sequence                uint64         `db:"sequence"`
	Kind                    string         `db:"kind"`
	Body                    string         `db:"body"`
	ImageID                 sql.NullInt64  `db:"image_id"`
	ImageContentType        sql.NullString `db:"image_content_type"`
	ImageByteSize           sql.NullInt32  `db:"image_byte_size"`
	FileID                  sql.NullInt64  `db:"file_id"`
	FileFilename            sql.NullString `db:"file_filename"`
	FileContentType         sql.NullString `db:"file_content_type"`
	FileByteSize            sql.NullInt32  `db:"file_byte_size"`
	CreatedAt               time.Time      `db:"created_at"`
}

func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]ListMessagesBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBefore,
		arg.ConversationID,
		arg.BeforeSequence,
		arg.UserID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesBeforeRow{}
	for rows.Next() {
		var i ListMessagesBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.SenderUsername,
			&i.SenderDisplayName,
			&i.SenderAvatarContentType,
			&i.SenderCreatedAt,
			&i.ClientMessageID,
			&i.Sequence,
			&i.Kind,
			&i.Body,
			&i.ImageID,
			&i.ImageContentType,
			&i.ImageByteSize,
			&i.FileID,
			&i.FileFilename,
			&i.FileContentType,
			&i.FileByteSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConversationForMessage = `-- name: LockConversationForMessage :one
SELECT conversation.next_sequence
FROM conversations AS conversation
JOIN conversation_members AS membership
  ON membership.conversation_id = conversation.id
WHERE conversation.id = ?
  AND membership.user_id = ?
LIMIT 1
FOR UPDATE
`

type LockConversationForMessageParams struct {
	ConversationID uint64 `db:"conversation_id"`
	UserID         uint64 `db:"user_id"`
}

func (q *Queries) LockConversationForMessage(ctx context.Context, arg LockConversationForMessageParams) (uint64, error) {
	row := q.db.QueryRowContext(ctx, lockConversationForMessage, arg.ConversationID, arg.UserID)
	var next_sequence uint64
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const recallMessage = `-- name: RecallMessage :execresult
UPDATE messages
SET recalled_at = CURRENT_TIMESTAMP(6)
WHERE id = ?
  AND conversation_id = ?
  AND sender_id = ?
  AND recalled_at IS NULL
  AND created_at >= CURRENT_TIMESTAMP(6) - INTERVAL 5 MINUTE
`

type RecallMessageParams struct {
	MessageID      uint64 `db:"message_id"`
	ConversationID uint64 `db:"conversation_id"`
	UserID         uint64 `db:"user_id"`
}

func (q *Queries) RecallMessage(ctx context.Context, arg RecallMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, recallMessage, arg.MessageID, arg.ConversationID, arg.UserID)
}
