// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"
)

type AccessToken struct {
	ID        uint64       `db:"id"`
	UserID    uint64       `db:"user_id"`
	TokenHash []byte       `db:"token_hash"`
	ExpiresAt time.Time    `db:"expires_at"`
	RevokedAt sql.NullTime `db:"revoked_at"`
	CreatedAt time.Time    `db:"created_at"`
}

type ContactRelationship struct {
	ID                uint64    `db:"id"`
	LowerUserID       uint64    `db:"lower_user_id"`
	HigherUserID      uint64    `db:"higher_user_id"`
	RequestedByUserID uint64    `db:"requested_by_user_id"`
	Status            string    `db:"status"`
	CreatedAt         time.Time `db:"created_at"`
	UpdatedAt         time.Time `db:"updated_at"`
}

type Conversation struct {
	ID                 uint64    `db:"id"`
	Kind               string    `db:"kind"`
	DirectLowerUserID  uint64    `db:"direct_lower_user_id"`
	DirectHigherUserID uint64    `db:"direct_higher_user_id"`
	CreatedByUserID    uint64    `db:"created_by_user_id"`
	CreatedAt          time.Time `db:"created_at"`
	UpdatedAt          time.Time `db:"updated_at"`
	NextSequence       uint64    `db:"next_sequence"`
}

type ConversationMember struct {
	ConversationID   uint64    `db:"conversation_id"`
	UserID           uint64    `db:"user_id"`
	JoinedAt         time.Time `db:"joined_at"`
	LastReadSequence uint64    `db:"last_read_sequence"`
}

type Message struct {
	ID              uint64        `db:"id"`
	ConversationID  uint64        `db:"conversation_id"`
	SenderID        uint64        `db:"sender_id"`
	ClientMessageID string        `db:"client_message_id"`
	Sequence        uint64        `db:"sequence"`
	Body            string        `db:"body"`
	CreatedAt       time.Time     `db:"created_at"`
	Kind            string        `db:"kind"`
	ImageID         sql.NullInt64 `db:"image_id"`
	FileID          sql.NullInt64 `db:"file_id"`
}

type MessageFile struct {
	ID          uint64    `db:"id"`
	UploaderID  uint64    `db:"uploader_id"`
	Filename    string    `db:"filename"`
	ContentType string    `db:"content_type"`
	ByteSize    uint32    `db:"byte_size"`
	Data        []byte    `db:"data"`
	CreatedAt   time.Time `db:"created_at"`
}

type MessageImage struct {
	ID          uint64    `db:"id"`
	UploaderID  uint64    `db:"uploader_id"`
	ContentType string    `db:"content_type"`
	ByteSize    uint32    `db:"byte_size"`
	Data        []byte    `db:"data"`
	CreatedAt   time.Time `db:"created_at"`
}

type RefreshToken struct {
	ID        uint64       `db:"id"`
	UserID    uint64       `db:"user_id"`
	TokenHash []byte       `db:"token_hash"`
	ExpiresAt time.Time    `db:"expires_at"`
	RevokedAt sql.NullTime `db:"revoked_at"`
	CreatedAt time.Time    `db:"created_at"`
}

type User struct {
	ID                uint64         `db:"id"`
	DisplayName       string         `db:"display_name"`
	PasswordHash      string         `db:"password_hash"`
	CreatedAt         time.Time      `db:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at"`
	Username          string         `db:"username"`
	Email             sql.NullString `db:"email"`
	Gender            sql.NullString `db:"gender"`
	Region            sql.NullString `db:"region"`
	AvatarContentType sql.NullString `db:"avatar_content_type"`
	AvatarData        sql.NullString `db:"avatar_data"`
}
