// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createPost = `-- name: CreatePost :execresult
INSERT INTO posts (author_id, body)
VALUES (?, ?)
`

type CreatePostParams struct {
	AuthorID uint64 `db:"author_id"`
	Body     string `db:"body"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPost, arg.AuthorID, arg.Body)
}

const createPostImage = `-- name: CreatePostImage :execresult
INSERT INTO post_images (
  post_id,
  position,
  content_type,
  byte_size,
  object_key
)
VALUES (?, ?, ?, ?, ?)
`

type CreatePostImageParams struct {
	PostID      uint64 `db:"post_id"`
	Position    uint8  `db:"position"`
	ContentType string `db:"content_type"`
	ByteSize    uint32 `db:"byte_size"`
	ObjectKey   string `db:"object_key"`
}

func (q *Queries) CreatePostImage(ctx context.Context, arg CreatePostImageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPostImage,
		arg.PostID,
		arg.Position,
		arg.ContentType,
		arg.ByteSize,
		arg.ObjectKey,
	)
}

const deletePostForAuthor = `-- name: DeletePostForAuthor :execresult
DELETE FROM posts
WHERE id = ?
  AND author_id = ?
`

type DeletePostForAuthorParams struct {
	PostID   uint64 `db:"post_id"`
	AuthorID uint64 `db:"author_id"`
}

func (q *Queries) DeletePostForAuthor(ctx context.Context, arg DeletePostForAuthorParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePostForAuthor, arg.PostID, arg.AuthorID)
}

const getPost = `-- name: GetPost :many
SELECT
  post.id,
  post.body,
  post.created_at,
  author.id AS author_id,
  author.username AS author_username,
  author.display_name AS author_display_name,
  author.avatar_content_type AS author_avatar_content_type,
  author.created_at AS author_created_at,
  image.id AS image_id,
  image.position AS image_position,
  image.content_type AS image_content_type,
  image.byte_size AS image_byte_size
FROM posts AS post
JOIN users AS author ON author.id = post.author_id
LEFT JOIN post_images AS image ON image.post_id = post.id
WHERE post.id = ?
ORDER BY image.position ASC
`

type GetPostRow struct {
	ID                      uint64         `db:"id"`
	Body                    string         `db:"body"`
	CreatedAt               time.Time      `db:"created_at"`
	AuthorID                uint64         `db:"author_id"`
	AuthorUsername          string         `db:"author_username"`
	AuthorDisplayName       string         `db:"author_display_name"`
	AuthorAvatarContentType sql.NullString `db:"author_avatar_content_type"`
	AuthorCreatedAt         time.Time      `db:"author_created_at"`
	ImageID                 sql.NullInt64  `db:"image_id"`
	ImagePosition           sql.NullInt16  `db:"image_position"`
	ImageContentType        sql.NullString `db:"image_content_type"`
	ImageByteSize           sql.NullInt32  `db:"image_byte_size"`
}

func (q *Queries) GetPost(ctx context.Context, postID uint64) ([]GetPostRow, error) {
	rows, err := q.db.QueryContext(ctx, getPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostRow{}
	for rows.Next() {
		var i GetPostRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarContentType,
			&i.AuthorCreatedAt,
			&i.ImageID,
			&i.ImagePosition,
			&i.ImageContentType,
			&i.ImageByteSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostImage = `-- name: GetPostImage :one
SELECT image.content_type, image.byte_size, image.object_key
FROM post_images AS image
JOIN posts AS post ON post.id = image.post_id
WHERE image.id = ?
LIMIT 1
`

type GetPostImageRow struct {
	ContentType string `db:"content_type"`
	ByteSize    uint32 `db:"byte_size"`
	ObjectKey   string `db:"object_key"`
}

func (q *Queries) GetPostImage(ctx context.Context, imageID uint64) (GetPostImageRow, error) {
	row := q.db.QueryRowContext(ctx, getPostImage, imageID)
	var i GetPostImageRow
	err := row.Scan(&i.ContentType, &i.ByteSize, &i.ObjectKey)
	return i, err
}

const listLatestPosts = `-- name: ListLatestPosts :many
SELECT
  page.id,
  page.body,
  page.created_at,
  author.id AS author_id,
  author.username AS author_username,
  author.display_name AS author_display_name,
  author.avatar_content_type AS author_avatar_content_type,
  author.created_at AS author_created_at,
  image.id AS image_id,
  image.position AS image_position,
  image.content_type AS image_content_type,
  image.byte_size AS image_byte_size
FROM (
  SELECT post.id, post.author_id, post.body, post.created_at
  FROM posts AS post
  ORDER BY post.id DESC
  LIMIT ?
) AS page
JOIN users AS author ON author.id = page.author_id
LEFT JOIN post_images AS image ON image.post_id = page.id
ORDER BY page.id DESC, image.position ASC
`

type ListLatestPostsRow struct {
	ID                      uint64         `db:"id"`
	Body                    string         `db:"body"`
	CreatedAt               time.Time      `db:"created_at"`
	AuthorID                uint64         `db:"author_id"`
	AuthorUsername          string         `db:"author_username"`
	AuthorDisplayName       string         `db:"author_display_name"`
	AuthorAvatarContentType sql.NullString `db:"author_avatar_content_type"`
	AuthorCreatedAt         time.Time      `db:"author_created_at"`
	ImageID                 sql.NullInt64  `db:"image_id"`
	ImagePosition           sql.NullInt16  `db:"image_position"`
	ImageContentType        sql.NullString `db:"image_content_type"`
	ImageByteSize           sql.NullInt32  `db:"image_byte_size"`
}

func (q *Queries) ListLatestPosts(ctx context.Context, limit int32) ([]ListLatestPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestPostsRow{}
	for rows.Next() {
		var i ListLatestPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarContentType,
			&i.AuthorCreatedAt,
			&i.ImageID,
			&i.ImagePosition,
			&i.ImageContentType,
			&i.ImageByteSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostObjectKeysForAuthor = `-- name: ListPostObjectKeysForAuthor :many
SELECT image.object_key
FROM posts AS post
JOIN post_images AS image ON image.post_id = post.id
WHERE post.id = ?
  AND post.author_id = ?
ORDER BY image.position ASC
`

type ListPostObjectKeysForAuthorParams struct {
	PostID   uint64 `db:"post_id"`
	AuthorID uint64 `db:"author_id"`
}

func (q *Queries) ListPostObjectKeysForAuthor(ctx context.Context, arg ListPostObjectKeysForAuthorParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPostObjectKeysForAuthor, arg.PostID, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsBefore = `-- name: ListPostsBefore :many
SELECT
  page.id,
  page.body,
  page.created_at,
  author.id AS author_id,
  author.username AS author_username,
  author.display_name AS author_display_name,
  author.avatar_content_type AS author_avatar_content_type,
  author.created_at AS author_created_at,
  image.id AS image_id,
  image.position AS image_position,
  image.content_type AS image_content_type,
  image.byte_size AS image_byte_size
FROM (
  SELECT post.id, post.author_id, post.body, post.created_at
  FROM posts AS post
  WHERE post.id < ?
  ORDER BY post.id DESC
  LIMIT ?
) AS page
JOIN users AS author ON author.id = page.author_id
LEFT JOIN post_images AS image ON image.post_id = page.id
ORDER BY page.id DESC, image.position ASC
`

type ListPostsBeforeParams struct {
	BeforePostID uint64 `db:"before_post_id"`
	Limit        int32  `db:"limit"`
}

type ListPostsBeforeRow struct {
	ID                      uint64         `db:"id"`
	Body                    string         `db:"body"`
	CreatedAt               time.Time      `db:"created_at"`
	AuthorID                uint64         `db:"author_id"`
	AuthorUsername          string         `db:"author_username"`
	AuthorDisplayName       string         `db:"author_display_name"`
	AuthorAvatarContentType sql.NullString `db:"author_avatar_content_type"`
	AuthorCreatedAt         time.Time      `db:"author_created_at"`
	ImageID                 sql.NullInt64  `db:"image_id"`
	ImagePosition           sql.NullInt16  `db:"image_position"`
	ImageContentType        sql.NullString `db:"image_content_type"`
	ImageByteSize           sql.NullInt32  `db:"image_byte_size"`
}

func (q *Queries) ListPostsBefore(ctx context.Context, arg ListPostsBeforeParams) ([]ListPostsBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsBefore, arg.BeforePostID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsBeforeRow{}
	for rows.Next() {
		var i ListPostsBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarContentType,
			&i.AuthorCreatedAt,
			&i.ImageID,
			&i.ImagePosition,
			&i.ImageContentType,
			&i.ImageByteSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportPost = `-- name: ReportPost :execresult
INSERT INTO post_reports (post_id, reporter_id, reason)
SELECT post.id, ?, ?
FROM posts AS post
WHERE post.id = ?
  AND post.author_id <> ?
ON DUPLICATE KEY UPDATE
  reason = VALUES(reason),
  created_at = CURRENT_TIMESTAMP(6)
`

type ReportPostParams struct {
	ReporterID uint64 `db:"reporter_id"`
	Reason     string `db:"reason"`
	PostID     uint64 `db:"post_id"`
}

func (q *Queries) ReportPost(ctx context.Context, arg ReportPostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, reportPost,
		arg.ReporterID,
		arg.Reason,
		arg.PostID,
		arg.ReporterID,
	)
}

const reportablePostExists = `-- name: ReportablePostExists :one
SELECT EXISTS (
  SELECT 1
  FROM posts
  WHERE id = ?
    AND author_id <> ?
) AS reportable_post_exists
`

type ReportablePostExistsParams struct {
	PostID     uint64 `db:"post_id"`
	ReporterID uint64 `db:"reporter_id"`
}

func (q *Queries) ReportablePostExists(ctx context.Context, arg ReportablePostExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, reportablePostExists, arg.PostID, arg.ReporterID)
	var reportable_post_exists bool
	err := row.Scan(&reportable_post_exists)
	return reportable_post_exists, err
}
