// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: realtime.sql

package store

import (
	"context"
)

const listProfileRecipientIDs = `-- name: ListProfileRecipientIDs :many
SELECT DISTINCT member.user_id
FROM conversation_members AS source
JOIN conversation_members AS member ON member.conversation_id = source.conversation_id
WHERE source.user_id = ?
  AND source.is_active = TRUE
  AND member.is_active = TRUE
ORDER BY member.user_id
`

func (q *Queries) ListProfileRecipientIDs(ctx context.Context, userID uint64) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, listProfileRecipientIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var user_id uint64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
